server:
  port: 9090

spring:
  application:
    name: microservice-authentication
  security:
    user:
      enabled: false
      name: ""
      password: ""

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:6543}/${DATABASE_NAME:postgresdb}
    username: ${USERNAME_AUTH:user}
    password: ${PASSWORD_AUTH:password}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
