server:
  port: 9090

spring:
  application:
    name: microservice-authentication
  security:
    user:
      enabled: false
      name: ""
      password: ""

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL_AUTH}
    username: ${USERNAME_AUTH}
    password: ${PASSWORD_AUTH}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.springframework.http: DEBUG
      org.springframework.security.authentication: DEBUG
      org.springframework.security.web: DEBUG
      org.springframework.security.access: DEBUG
      org.springframework.boot: DEBUG

