server:
  port: 8090

spring:
  application:
    name: microservice-movies

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL_MOVIES}
    username: ${USERNAME_MOVIES}
    password: ${PASSWORD_MOVIES}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
